version: "3.8"

services:
  rabbitmq3:
    container_name: rabbitmq
    image: rabbitmq:3-management 
    ports: 
      - 15672:15672
      - 5672:5672

# docker inspect rabbitmq:3-management | grep tcp
# dc up -d